"""Universal entity base.

Every node in the v2 graph is an ``Entity`` subclass. Each subclass declares
its ``kind`` as a ``ClassVar[EntityKind]``. See §1.3 of the plan.

Auto-generated ref resolvers
----------------------------
For every ``*_ref`` / ``*_refs`` field on a concrete ``Entity`` subclass,
``__pydantic_init_subclass__`` installs a same-named method that resolves
the ref through an explicit ``graph`` argument:

    class Commit(Entity):
        author_ref: EntityRef
        parent_refs: list[EntityRef] = []

    commit.author(graph)   # -> Optional[GitAccount]
    commit.parents(graph)  # -> list[Commit]   (unresolved entries dropped)

Singular fields strip ``_ref``; list fields strip ``_refs``. Optional
singular fields (``Optional[EntityRef] = None``) resolve to ``None`` when
the field itself is ``None``. A name collision with an existing attribute
raises ``TypeError`` at class-build time — never silent shadowing.

Value objects that are ``BaseModel`` but not ``Entity`` (e.g. the Jira
``Comment`` / ``IssueTransition`` records embedded inside ``Issue``) can
opt in by decorating with :func:`with_ref_resolvers`.
"""
from __future__ import annotations

from abc import ABC
from typing import Any, ClassVar, get_args, get_origin

from pydantic import BaseModel, ConfigDict

from .kinds import EntityKind
from .ref import EntityRef


def _entity_reconstruct(cls: type["Entity"], state: dict[str, Any]) -> "Entity":
    """Module-level helper so pickle can find it by qualname."""
    return cls.from_state(state)


def _resolver_name(fname: str) -> str | None:
    """Return the generated method name for a ref-field, or ``None``.

    Convention in this codebase: list-of-refs fields are named
    ``<singular>_refs`` (``parent_refs``, ``commit_refs``,
    ``review_comment_refs``). The generated method is the plural form
    obtained by stripping ``_refs`` and appending ``s``::

        parent_refs        -> parents
        commit_refs        -> commits
        review_comment_refs -> review_comments

    Singular fields strip ``_ref``::

        author_ref         -> author
    """
    if fname.endswith("_refs"):
        stem = fname[:-5]
        if stem.endswith("s"):
            raise TypeError(
                f"Field {fname!r} would generate resolver name "
                f"{stem + 's'!r} (double-pluralized). Rename the field "
                f"to <singular>_refs, or extend ``_resolver_name`` in "
                f"``kernel/entity.py`` with an irregular-plural rule."
            )
        return stem + "s"
    if fname.endswith("_ref"):
        return fname[:-4]
    return None


def _strip_optional(annotation: Any) -> Any:
    """Peel a single ``Optional[T]`` / ``T | None`` wrapper, return T."""
    origin = get_origin(annotation)
    # typing.Union / types.UnionType both report origin handled by get_args
    if origin is None:
        return annotation
    args = [a for a in get_args(annotation) if a is not type(None)]  # noqa: E721
    if len(args) == 1 and len(get_args(annotation)) == 2:
        return args[0]
    return annotation


def _is_list_of_refs(annotation: Any) -> bool:
    """True iff ``annotation`` is ``list[EntityRef]`` / ``List[EntityRef]``
    (optionally wrapped in ``Optional``)."""
    inner = _strip_optional(annotation)
    origin = get_origin(inner)
    if origin is None or origin is not list:
        return False
    args = get_args(inner)
    return len(args) == 1 and args[0] is EntityRef


def _is_single_ref(annotation: Any) -> bool:
    """True iff ``annotation`` is ``EntityRef`` (optionally Optional)."""
    inner = _strip_optional(annotation)
    return inner is EntityRef


def _make_resolver(fname: str, is_list: bool):
    """Build the resolver function for one field.

    Uses :meth:`Graph.resolve` rather than :meth:`EntityRef.resolve` so
    multi-registry kinds (``EntityKind.PROJECT`` has 7 candidate
    registries) work transparently. For single-registry kinds the two
    are equivalent.
    """
    method_name = _resolver_name(fname)
    if is_list:
        def resolver(self, graph):
            refs = getattr(self, fname, None) or ()
            out = []
            for ref in refs:
                ent = graph.resolve(ref)
                if ent is not None:
                    out.append(ent)
            return out
    else:
        def resolver(self, graph):
            ref = getattr(self, fname, None)
            return None if ref is None else graph.resolve(ref)

    resolver.__name__ = method_name
    resolver.__qualname__ = method_name
    resolver.__doc__ = (
        f"Resolve ``self.{fname}`` through ``graph``. "
        f"Generated by ``Entity.__pydantic_init_subclass__``; "
        f"see ``kernel/entity.py``."
    )
    # Marker so we can distinguish our installs from real user methods
    # (idempotency on re-import, honest collision detection).
    resolver._generated_ref_resolver = True  # type: ignore[attr-defined]
    return resolver


def _install_ref_resolvers(cls: type[BaseModel]) -> None:
    """Inject a resolver method for every ``*_ref`` / ``*_refs`` field.

    * Singular field ``foo_ref`` (or ``Optional[EntityRef]``) → method
      ``foo(graph) -> Optional[Entity]``.
    * List field ``foo_refs: list[EntityRef]`` → method
      ``foo(graph) -> list[Entity]`` with unresolved entries dropped.

    Raises ``TypeError`` if a generated name would shadow an attribute the
    user wrote themselves; previous generator installs (marked with
    ``_generated_ref_resolver``) are silently replaced for re-import
    idempotency.
    """
    for fname, finfo in cls.model_fields.items():
        method_name = _resolver_name(fname)
        if method_name is None:
            continue
        is_list = _is_list_of_refs(finfo.annotation)
        is_single = _is_single_ref(finfo.annotation)
        if not (is_list or is_single):
            # Field ends in _ref/_refs but its declared type is not
            # EntityRef — leave it alone, the author has a different
            # contract in mind.
            continue
        existing = cls.__dict__.get(method_name)
        if existing is not None and not getattr(
            existing, "_generated_ref_resolver", False
        ):
            raise TypeError(
                f"{cls.__name__}.{method_name} would be auto-generated from "
                f"field {fname!r}, but the class already defines "
                f"{method_name!r}. Rename the ref field or remove the "
                f"colliding attribute."
            )
        setattr(cls, method_name, _make_resolver(fname, is_list))


def with_ref_resolvers(cls: type[BaseModel]) -> type[BaseModel]:
    """Decorator that runs the ref-resolver generator on any ``BaseModel``.

    Use on value objects (``BaseModel`` subclasses that aren't ``Entity``)
    so they get the same ``.author(graph)`` / ``.commits(graph)`` shape:

        @with_ref_resolvers
        class Comment(BaseModel):
            author_ref: EntityRef
            ...
    """
    _install_ref_resolvers(cls)
    return cls


class Entity(BaseModel, ABC):
    """Common base for every graph node.

    Concrete subclasses MUST override ``kind`` with the matching
    ``EntityKind`` member. ``extra="forbid"`` enforces the "no untyped
    attributes" rule at validation time.
    """

    # Subclasses override this ClassVar. The base intentionally has no
    # default — concrete subclasses are validated by ``__init_subclass__``.
    kind: ClassVar[EntityKind]

    model_config = ConfigDict(frozen=False, extra="forbid")

    id: str

    def __init_subclass__(cls, abstract: bool = False, **kwargs: Any) -> None:
        """Validate that every concrete subclass declares ``kind``.

        Intermediate abstract bases (e.g. ``Account``, ``Tag``) opt out by
        passing ``abstract=True`` in the class statement::

            class Account(Entity, abstract=True):
                name: str
                ...

        Concrete leaves MUST declare ``kind`` either on the class itself or
        on a (non-Entity) ancestor in the MRO.
        """
        super().__init_subclass__(**kwargs)
        # Pydantic re-runs __init_subclass__ on its synthesized subclass
        # machinery; treat ABC-flagged classes (with unresolved
        # __abstractmethods__) as abstract too.
        if abstract or getattr(cls, "__abstractmethods__", None):
            # Stash the flag on the class for downstream introspection
            # (e.g. ``LazyRegistryProxy`` does not need it but tooling may).
            cls.__entity_abstract__ = True
            return
        cls.__entity_abstract__ = False
        if "kind" not in cls.__dict__:
            declared = False
            for base in cls.__mro__[1:]:
                if base is Entity:
                    break
                if "kind" in base.__dict__:
                    declared = True
                    break
            if not declared:
                raise TypeError(
                    f"Concrete Entity subclass {cls.__name__!r} must declare "
                    f"``kind: ClassVar[EntityKind] = EntityKind.<X>``. Pass "
                    f"``abstract=True`` in the class statement to opt out "
                    f"(intermediate bases like Account/Tag)."
                )

    @classmethod
    def __pydantic_init_subclass__(cls, **kwargs: Any) -> None:
        """Install ref-resolver methods.

        Pydantic populates ``model_fields`` *after* ``__init_subclass__``
        returns; this hook is the supported way to react to a fully-built
        subclass. Abstract intermediate bases (``__entity_abstract__``)
        are skipped — their concrete children get the resolvers.
        """
        super().__pydantic_init_subclass__(**kwargs)
        if getattr(cls, "__entity_abstract__", False):
            return
        _install_ref_resolvers(cls)

    def ref(self) -> EntityRef:
        """Return a typed pointer to this entity."""
        return EntityRef(kind=type(self).kind, id=self.id)

    # ------------------------------------------------------------------
    # Pickle hooks. The default behavior delegates to Pydantic
    # ``model_dump`` / ``model_validate`` so every Entity is picklable
    # without each subclass writing its own ``__reduce__``. Subclasses can
    # override either method to customize serialization. See §6/§8.
    # ------------------------------------------------------------------
    def __reduce__(self) -> tuple[Any, ...]:
        state = self.model_dump(mode="python")
        return (_entity_reconstruct, (type(self), state))

    @classmethod
    def from_state(cls, state: dict[str, Any]) -> "Entity":
        """Reconstruct an instance from a ``model_dump`` payload."""
        return cls.model_validate(state)


__all__ = ["Entity", "with_ref_resolvers"]
